### ISSUE TITLE
linux from github source does not sync

### ISSUE THREAD

**Issue by collapsedev** [AMCcoin/AmericanCoin#1]
received block 5869b89b8ab4717e9ca9
InvalidChainFound: invalid block=5869b89b8ab4717e9ca9  height=1  work=2097184  date=25/05/13 20:47:21
InvalidChainFound:  current best=e235425c8314df2f26b9  height=0  work=1048592  date=25/05/13 03:37:12
ERROR: SetBestChain() : SetBestChainInner failed
ERROR: AcceptBlock() : AddToBlockIndex failed
ERROR: ProcessBlock() : AcceptBlock FAILED
received block 11fd60dca88266f4635c
Postponing 1 reconnects

**Comment by AMCcoin** [comment]
Investigating now; built fine earlier

**Comment by AMCcoin** [comment]
This has been resolved in the new genesis & branch going forward.
